apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: pingpong-counter
          persistentVolumeClaim:
            claimName: pingpong-claim
      containers:
        - name: log-output
          image: sashausoskin/log-output:v7
          env:
          - name: PING_PONG_URL
            value: "http://ping-pong-svc:2345"