apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output
          emptyDir: {}
      containers:
        - name: log-output
          image: sashausoskin/log-output:v3
          volumeMounts:
          - name: log-output
            mountPath: /usr/src/app/files
        - name: log-getter
          image: sashausoskin/log-getter:v1
          volumeMounts:
          - name: log-output
            mountPath: /usr/src/app/files