apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: sashausoskin/ping-pong:v5
          env:
            - name: POSTGRES_URL
              value: postgresql://postgres:secret@postgres-svc:5432/postgres
            - name: PORT
              value: "3000"
