apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
      - name: pingpong-counter
        persistentVolumeClaim:
          claimName: pingpong-claim
      containers:
        - name: ping-pong
          image: sashausoskin/ping-pong:v3
          volumeMounts:
            - name: pingpong-counter
              mountPath: /usr/src/app/pingpong