apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: sashausoskin/image-service:v2
          env:
          - name: PORT
            value: "3002"
          - name: PICSUM_URL
            value: 'https://picsum.photos/3000'